package org.najim.compiler.tokenizer;

/**
 * <p>Indicates the type of {@link Token} that was generated by a {@link Tokenizer}.</p>
 * 
 * @author Brendan Jones
 *
 */
public enum TokenType {
	
	/**
	 * <p>A token that is enclosed in a pair of either single-quotes ('') or a pair
	 * of double-quotes ("").</p>
	 */
	STRING_LITERAL,

	OPEN_PARENTHESIS,
	
	CLOSE_PARENTHESIS,
	
	OPEN_BRACKET,
	
	CLOSE_BRACKET,
	
	OPEN_BRACE,
	
	CLOSE_BRACE,
	
	STATEMENT_TERMINAL,
	
	IDENTIFIER,
	
	KEYWORD_IF,
	
	KEYWORD_ELSE,
	
	KEYWORD_FUNCTION,
	
	KEYWORD_FOR,
	
	KEYWORD_WHILE,
	
	KEYWORD_TRUE,
	
	KEYWORD_FALSE,

	TYPE_INT,
	
	TYPE_BOOL,
	
	TYPE_REAL,
	
	TYPE_STRING,
		
	OP_ASSIGN,
		
	OP_ADD,
	
	OP_ADD_ASSIGN,
	
	OP_SUB,
	
	OP_SUB_ASSIGN,
	
	OP_MULT,
	
	OP_MULT_ASSIGN,
	
	OP_DIV,
	
	OP_DIV_ASSIGN,
	
	OP_MOD,
	
	OP_MOD_ASSIGN,
	
	OP_POW,
	
	OP_POW_ASSIGN,
	
	OP_AND,
	
	OP_AND_ASSIGN,
	
	OP_OR,
	
	OP_OR_ASSIGN,

	OP_NOT,
	
	OP_LESS,
	
	OP_LESS_EQUAL,
	
	OP_EQUAL,
	
	OP_NOT_EQUAL,

	OP_GREATER_EQUAL,
	
	OP_GREATER,
			
}
